// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srdtlfcvmiiukgaeuhsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyZHRsZmN2bWlpdWtnYWV1aHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjE5MTEsImV4cCI6MjA3Mjg5NzkxMX0.ndJsIJt-19N7BmEmUOVGctvGZPZZb5vcV2XUWS1sl4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});